name: Android Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Version Name
        id: get_version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle | awk -F'"' '{print $2}')
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Check if Tag exists
        id: check_tag
        run: |
          if git rev-parse "${{ steps.get_version.outputs.tag }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.get_version.outputs.tag }} already exists. Skipping release steps."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Decode Keystore
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ github.workspace }}/release.jks

      - name: Build and Sign Release APK
        if: steps.check_tag.outputs.exists == 'false'
        run: ./gradlew assembleRelease
        env:
          SIGNING_STORE_FILE: ${{ github.workspace }}/release.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          name: Release v${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.tag }}
          body: |
           ### Automatic Release
            - **Version**: ${{ steps.get_version.outputs.version }}
            - **Build Date**: ${{ github.event.head_commit.timestamp }}
            - **Commit Message**: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
